version: '3'
services:
  back:
    build: back
    volumes:
      - ./back:/chat
      - bundle:/usr/local/bundle
    command: bash -c "rm -f /app/tmp/pids/server.pid && rails s -p 8000 -b 0.0.0.0"
    depends_on:
      - db
    ports:
      - 8000:8000

  front:
    build: front
    volumes:
      - ./front:/app
    working_dir: /app/react-project
    command: yarn start
    ports:
      - 3000:3000
    tty: true

  db:
    image: mysql:8.0.16
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build: server
    volumes:
      #- ./server/nginx.conf:/etc/nginx/conf.d/nginx.conf #buildしなくいいように
      - ./server/ssl:/etc/nginx/ssl
    depends_on:
      - back
      - front
    ports:
      - 443:443

volumes:
  bundle:
  mysql-data:
